project:
  type: website

website:
  title: "fmon-docs"
  navbar:
    left:
      - href: index.qmd
        text: Getting Started
      - href: gui.qmd
        text: GUI
      - href: bonsai.qmd
        text: Bonsai
      - href: bpod.qmd
        text: Bpod
      - href: hardware.qmd
        text: Hardware
      - href: cad.qmd
        text: CAD
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



