project:
  type: website

website:
  title: "fmon-docs"
  navbar:
    left:
      - href: index.qmd
        text: Getting Started
      - href: gui.qmd
        text: GUI
      - href: bonsai.qmd
        text: Bonsai
      - href: bpod.qmd
        text: Bpod Protocol
      - href: hardware.qmd
        text: Hardware
      - href: data.qmd
        text: Data
      - href: about.qmd
        text: About
    tools:
        - icon: github
          href: https://github.com/nghess/fmon-bpod

format:
  html:
    theme: Cyborg
    css: styles.css
    toc: true


jupyter:
  kernel: python3



